import random
import itertools
import collections

class Node:
    """
    A class representing an Solver node
    - 'puzzle' is a Puzzle instance
    - 'parent' is the preceding node generated by the solver, if any
    - 'action' is the action taken to produce puzzle, if any
    """
    def __init__(self, puzzle, parent=None, action=None):
        self.puzzle = puzzle
        self.parent = parent
        self.action = action
        if (self.parent != None):
            self.g = parent.g + 1
        else:
            self.g = 0

    @property
    def score(self):
        return (self.g + self.h)

    @property
    def state(self):
        """
        Return a hashable representation of self
        """
        return str(self)

    @property 
    def path(self):
        """
        Reconstruct a path from to the root 'parent'
        """
        node, p = self, []
        while node:
            p.append(node)
            node = node.parent
        yield from reversed(p)

    @property
    def solved(self):
        """ Wrapper to check if 'puzzle' is solved """
        return self.puzzle.solved

    @property
    def actions(self):
        """ Wrapper for 'actions' accessible at current state """
        return self.puzzle.actions

    @property
    def h(self):
        """"h"""
        return self.puzzle.manhattan

    @property
    def f(self):
        """"f"""
        return self.h + self.g

    def __str__(self):
        return str(self.puzzle)

class Solver:
    """
    An '8-puzzle' solver
    - 'start' is a Puzzle instance
    """
    def __init__(self, start):
        self.start = start

    def solve(self):
        """
        Perform breadth first search and return a path
        to the solution, if it exists
        """
        queue = collections.deque([Node(self.start)])
        seen = set()
        seen.add(queue[0].state)
        while queue:
            queue = collections.deque(sorted(list(queue), key=lambda node: node.f))
            node = queue.popleft()
            if node.solved:
                return node.path

            for move, action in node.actions:
                child = Node(move(), node, action)

                if child.state not in seen:
                    queue.appendleft(child)
                    seen.add(child.state)

    def dfs(self, depth_limit, iteration_limit):
        stack = [Node(self.start)]
        seen = set()
        seen.add(stack[0].state)
        visited_nodes = []
        iterations = 0

        while stack and iterations < iteration_limit:
            node = stack.pop()
            visited_nodes.append(node)
            iterations += 1

            if node.solved:
                return node.path

            if node.g < depth_limit:
                for move, action in node.actions:
                    child = Node(move(), node, action)

                    if child.state not in seen:
                        stack.append(child)
                        seen.add(child.state)

        return None  # Trả về danh sách các node đã đi qua nếu không tìm thấy giải pháp trong giới hạn độ sâu hoặc giới hạn lặp

    def bfs(self, depth_limit, iteration_limit):
        queue = collections.deque([Node(self.start)])
        seen = set()
        seen.add(queue[0].state)
        visited_nodes = []
        iterations = 0

        while queue and iterations < iteration_limit:
            queue = collections.deque(sorted(list(queue), key=lambda node: node.f))
            node = queue.popleft()
            visited_nodes.append(node)
            iterations += 1

            if node.solved:
                return node.path

            if node.g < depth_limit:
                for move, action in node.actions:
                    child = Node(move(), node, action)

                    if child.state not in seen:
                        queue.appendleft(child)
                        seen.add(child.state)

        return None 
class Puzzle:
    """
    A class representing an '8-puzzle'.
    - 'board' should be a square list of lists with integer entries 0...width^2 - 1
       e.g. [[1,2,3],[4,0,6],[7,5,8]]
    """
    def __init__(self, board):
        self.width = len(board[0])
        self.board = board

    @property
    def solved(self):
        """
        The puzzle is solved if the flattened board's numbers are in
        increasing order from left to right and the '0' tile is in the
        last position on the board
        """
        N = self.width * self.width
        return str(self) == ''.join(map(str, range(1,N))) + '0'

    @property 
    def actions(self):
        """
        Return a list of 'move', 'action' pairs. 'move' can be called
        to return a new puzzle that results in sliding the '0' tile in
        the direction of 'action'.
        """
        def create_move(at, to):
            return lambda: self._move(at, to)

        moves = []
        for i, j in itertools.product(range(self.width),
                                      range(self.width)):
            direcs = {'R':(i, j-1),
                      'L':(i, j+1),
                      'D':(i-1, j),
                      'U':(i+1, j)}

            for action, (r, c) in direcs.items():
                if r >= 0 and c >= 0 and r < self.width and c < self.width and \
                   self.board[r][c] == 0:
                    move = create_move((i,j), (r,c)), action
                    moves.append(move)
        return moves

    @property
    def manhattan(self):
        distance = 0
        for i in range(3):
            for j in range(3):
                if self.board[i][j] != 0:
                    x, y = divmod(self.board[i][j]-1, 3)
                    distance += abs(x - i) + abs(y - j)
        return distance

    def isSolvable(self):
        inversions = 0
        flatten_board = [num for row in self.board for num in row if num != 0]

        for i in range(len(flatten_board)):
            for j in range(i + 1, len(flatten_board)):
                if flatten_board[i] > flatten_board[j]:
                    inversions += 1
        return inversions % 2 == 0

    def copy(self):
        """
        Return a new puzzle with the same board as 'self'
        """
        board = []
        for row in self.board:
            board.append([x for x in row])
        return Puzzle(board)

    def _move(self, at, to):
        """
        Return a new puzzle where 'at' and 'to' tiles have been swapped.
        NOTE: all moves should be 'actions' that have been executed
        """
        copy = self.copy()
        i, j = at
        r, c = to
        copy.board[i][j], copy.board[r][c] = copy.board[r][c], copy.board[i][j]
        return copy

    def __str__(self):
        return ''.join(map(str, self))

    def __iter__(self):
        for row in self.board:
            yield from row

            

# example of use     
#board = [[1,2,3],[4,5,0],[6,7,8]]
# board = [[7, 1, 2], [5, 6, 3], [4, 8, 0]]
# puzzle = Puzzle(board)
# puzzle = puzzle.shuffle()
# s = Solver(puzzle)
# #tic = time.clock()
# tic=time.perf_counter()
# p = s.solve()
# toc = time.perf_counter()

# steps = 0
# for node in p:
#     print(node.action)
#     node.puzzle.pprint()
#     steps += 1

# print("Total number of steps: " + str(steps))
# print("Total amount of time in search: " + str(toc - tic) + " second(s)")